### ISSUE TITLE
Problems running toybox install with one dependency

### ISSUE THREAD

**Issue by DidierMalenfant** [jm/toybox#2]
I have a `Boxfile` in my modplayer library which contains this:
```
{
	"DidierMalenfant/pdutility": "toybox"
}
```
when running `toybox install` I get this:
```
 🧸toybox v.0.0.3
 INFO.  It is highly recommended you log in to GitHub!
 INFO.  Use `toybox login` to avoid GitHub API limits.
 Loading Boxfile...
 Resolving dependencies...
 ERROR  Failed to resolve versions
```
It looks like replacing the name of the branch with `default` works.

Any way to get more info regarding the error?

**Comment by jm** [comment]
Hmm I'll look into this one.  I have a few theories
