### ISSUE TITLE
toybox add doesn't work when no Boxfile is present

### ISSUE THREAD

**Issue by DidierMalenfant** [jm/toybox#3]
When I try to add a new toybox to a project that doesn't have yet a `Boxfile` I get the following error:
```
 🧸toybox v.0.0.3
 ERROR  Error reading Boxfile: 
 open Boxfile: no such file or directory
```
It may be useful for toybox to create that file if it's not already there.

Note: If the `Boxfile` exists but it empty, you also get an error instead of toybox adding the dependency.

**Comment by jm** [comment]
Oh good call!  I'll add that and add some handling for blank files.
