### ISSUE TITLE
toybox accessing the local network during execution

### ISSUE THREAD

**Issue by DidierMalenfant** [jm/toybox#4]
When running the app, it seems to be trying to access things on my local network (little snitch catches the requests). Is there any reason you can think of for this?

**Comment by jm** [comment]
That's weird.  What is it attempting to access exactly?  I can't fathom why that would be!

**Comment by DidierMalenfant** [comment]
Not sure. I got some IPV6 address a couple of times and then my local router (as in directly via its IP).

What is the app using in terms of API to access GitHub? Could be that.

**Comment by jm** [comment]
Yep it makes several API requests, but weird that it would try to access something on your local network?  Or is it just showing the requests out to GitHub?
